"""Fixe Domänenzuweisungen für die 100 Testfälle."""
from __future__ import annotations


DOMAIN_ASSIGNMENTS: list[dict] = [
    # Stufe 1: 33 Testfälle (TC001–TC033)
    {"id": "TC001", "stufe": 1, "domaene": "Bibliothek"},
    {"id": "TC002", "stufe": 1, "domaene": "Tierarztpraxis"},
    {"id": "TC003", "stufe": 1, "domaene": "Fitnessstudio"},
    {"id": "TC004", "stufe": 1, "domaene": "Buchhandlung"},
    {"id": "TC005", "stufe": 1, "domaene": "Autowerkstatt"},
    {"id": "TC006", "stufe": 1, "domaene": "Musikschule"},
    {"id": "TC007", "stufe": 1, "domaene": "Fahrradverleih"},
    {"id": "TC008", "stufe": 1, "domaene": "Hundesalon"},
    {"id": "TC009", "stufe": 1, "domaene": "Reinigung"},
    {"id": "TC010", "stufe": 1, "domaene": "Videothek"},
    {"id": "TC011", "stufe": 1, "domaene": "Zahnarztpraxis"},
    {"id": "TC012", "stufe": 1, "domaene": "Optiker"},
    {"id": "TC013", "stufe": 1, "domaene": "Friseursalon"},
    {"id": "TC014", "stufe": 1, "domaene": "Malergeschäft"},
    {"id": "TC015", "stufe": 1, "domaene": "Nachhilfeinstitut"},
    {"id": "TC016", "stufe": 1, "domaene": "Sportverein"},
    {"id": "TC017", "stufe": 1, "domaene": "Gartenmarkt"},
    {"id": "TC018", "stufe": 1, "domaene": "Kindertagesstätte"},
    {"id": "TC019", "stufe": 1, "domaene": "Bäckerei"},
    {"id": "TC020", "stufe": 1, "domaene": "Fotoatelier"},
    {"id": "TC021", "stufe": 1, "domaene": "Pflanzenmarkt"},
    {"id": "TC022", "stufe": 1, "domaene": "Spielzeuggeschäft"},
    {"id": "TC023", "stufe": 1, "domaene": "Schreibwarengeschäft"},
    {"id": "TC024", "stufe": 1, "domaene": "Blumenladen"},
    {"id": "TC025", "stufe": 1, "domaene": "Schuhreparatur"},
    {"id": "TC026", "stufe": 1, "domaene": "Schlosserei"},
    {"id": "TC027", "stufe": 1, "domaene": "Weinhandlung"},
    {"id": "TC028", "stufe": 1, "domaene": "Coffeeshop"},
    {"id": "TC029", "stufe": 1, "domaene": "Fischhandel"},
    {"id": "TC030", "stufe": 1, "domaene": "Pizzalieferdienst"},
    {"id": "TC031", "stufe": 1, "domaene": "Mietfahrrad"},
    {"id": "TC032", "stufe": 1, "domaene": "Spielplatz"},
    {"id": "TC033", "stufe": 1, "domaene": "Hundehotel"},

    # Stufe 2: 33 Testfälle (TC034–TC066)
    {"id": "TC034", "stufe": 2, "domaene": "Hotelverwaltung"},
    {"id": "TC035", "stufe": 2, "domaene": "Restaurantkette"},
    {"id": "TC036", "stufe": 2, "domaene": "Schulverwaltung"},
    {"id": "TC037", "stufe": 2, "domaene": "Arztpraxis"},
    {"id": "TC038", "stufe": 2, "domaene": "Immobilienmakler"},
    {"id": "TC039", "stufe": 2, "domaene": "Reisebüro"},
    {"id": "TC040", "stufe": 2, "domaene": "Autovermietung"},
    {"id": "TC041", "stufe": 2, "domaene": "Kursverwaltung"},
    {"id": "TC042", "stufe": 2, "domaene": "Eventmanagement"},
    {"id": "TC043", "stufe": 2, "domaene": "Apotheke"},
    {"id": "TC044", "stufe": 2, "domaene": "Versicherungsagentur"},
    {"id": "TC045", "stufe": 2, "domaene": "Personalverwaltung"},
    {"id": "TC046", "stufe": 2, "domaene": "Lagerverwaltung"},
    {"id": "TC047", "stufe": 2, "domaene": "Ticketsystem"},
    {"id": "TC048", "stufe": 2, "domaene": "Kundendienst"},
    {"id": "TC049", "stufe": 2, "domaene": "Bankverwaltung"},
    {"id": "TC050", "stufe": 2, "domaene": "Lieferdienst"},
    {"id": "TC051", "stufe": 2, "domaene": "Freelancer-Plattform"},
    {"id": "TC052", "stufe": 2, "domaene": "Coworking-Space"},
    {"id": "TC053", "stufe": 2, "domaene": "Sportliga"},
    {"id": "TC054", "stufe": 2, "domaene": "Musikfestival"},
    {"id": "TC055", "stufe": 2, "domaene": "Messeverwaltung"},
    {"id": "TC056", "stufe": 2, "domaene": "Jugendzentrum"},
    {"id": "TC057", "stufe": 2, "domaene": "Bibliotheksnetzwerk"},
    {"id": "TC058", "stufe": 2, "domaene": "Fuhrpark"},
    {"id": "TC059", "stufe": 2, "domaene": "Wohnungsvermittlung"},
    {"id": "TC060", "stufe": 2, "domaene": "Handwerksplattform"},
    {"id": "TC061", "stufe": 2, "domaene": "Abonnementverwaltung"},
    {"id": "TC062", "stufe": 2, "domaene": "Projektmanagementtool"},
    {"id": "TC063", "stufe": 2, "domaene": "Bürgerserviceportal"},
    {"id": "TC064", "stufe": 2, "domaene": "Energieversorger"},
    {"id": "TC065", "stufe": 2, "domaene": "Lieferkettenmanagement"},
    {"id": "TC066", "stufe": 2, "domaene": "Bestellplattform"},

    # Stufe 3: 34 Testfälle (TC067–TC100)
    {"id": "TC067", "stufe": 3, "domaene": "Krankenhausverwaltung"},
    {"id": "TC068", "stufe": 3, "domaene": "Universitätsverwaltung"},
    {"id": "TC069", "stufe": 3, "domaene": "Produktionsplanung"},
    {"id": "TC070", "stufe": 3, "domaene": "Forschungsdatenverwaltung"},
    {"id": "TC071", "stufe": 3, "domaene": "Bankkernbanksystem"},
    {"id": "TC072", "stufe": 3, "domaene": "Logistiknetzwerk"},
    {"id": "TC073", "stufe": 3, "domaene": "Gesundheitsversorgungsnetzwerk"},
    {"id": "TC074", "stufe": 3, "domaene": "Rechtskanzlei"},
    {"id": "TC075", "stufe": 3, "domaene": "Pharmazeutische Forschung"},
    {"id": "TC076", "stufe": 3, "domaene": "Energiehandel"},
    {"id": "TC077", "stufe": 3, "domaene": "Flughafenverwaltung"},
    {"id": "TC078", "stufe": 3, "domaene": "Bauprojektverwaltung"},
    {"id": "TC079", "stufe": 3, "domaene": "Sozialversicherungssystem"},
    {"id": "TC080", "stufe": 3, "domaene": "Steuerverwaltung"},
    {"id": "TC081", "stufe": 3, "domaene": "Katastrophenschutzsystem"},
    {"id": "TC082", "stufe": 3, "domaene": "Telekommunikationsnetz"},
    {"id": "TC083", "stufe": 3, "domaene": "Börsenverwaltung"},
    {"id": "TC084", "stufe": 3, "domaene": "Wissenschaftliches Publikationssystem"},
    {"id": "TC085", "stufe": 3, "domaene": "Militärlogistik"},
    {"id": "TC086", "stufe": 3, "domaene": "Raumfahrtprojektverwaltung"},
    {"id": "TC087", "stufe": 3, "domaene": "Medizinische Geräteregistrierung"},
    {"id": "TC088", "stufe": 3, "domaene": "Internationale Handelsverwaltung"},
    {"id": "TC089", "stufe": 3, "domaene": "Patientendatenmanagementsystem"},
    {"id": "TC090", "stufe": 3, "domaene": "Smart-City-Plattform"},
    {"id": "TC091", "stufe": 3, "domaene": "Digitale Zwillingsverwaltung"},
    {"id": "TC092", "stufe": 3, "domaene": "Biobankdatenbank"},
    {"id": "TC093", "stufe": 3, "domaene": "Klinische Studienverwaltung"},
    {"id": "TC094", "stufe": 3, "domaene": "Nationalarchiv"},
    {"id": "TC095", "stufe": 3, "domaene": "Kulturerbe-Inventarsystem"},
    {"id": "TC096", "stufe": 3, "domaene": "Komplexe Lieferkette"},
    {"id": "TC097", "stufe": 3, "domaene": "Mehrmandantensoftware"},
    {"id": "TC098", "stufe": 3, "domaene": "Notfallmanagementsystem"},
    {"id": "TC099", "stufe": 3, "domaene": "Regulatorische Compliance-Plattform"},
    {"id": "TC100", "stufe": 3, "domaene": "Grosshandels-ERP-System"},
]


assert len(DOMAIN_ASSIGNMENTS) == 100, "Es müssen exakt 100 Domänenzuweisungen vorhanden sein."
